### ISSUE TITLE
receive sms

### ISSUE THREAD

**Issue by oumaroulabo** [d4rkstar/yii2-kannel#2]
Hello how are you,
I appreciated your code, it's cool,
I would like to know if it is possible to receive sms from your widget?
If yes how to do it, show me if possible the steps to follow ... Pending

**Comment by d4rkstar** [comment]
Hello,
the code is not intended for receive SMS. Just send.

In yii2 you can receive SMS implementing a route to receive sms. Please check docs here:

https://www.kannel.org/download/1.4.5/userguide-1.4.5/userguide.html

get-url or post-url 

Regards

**Comment by oumaroulabo** [comment]
Hi,
thank you but I use Laravel framework . Nice docs...
